### ISSUE TITLE
BT is on, but LYWDSD02 says "bluetooth off"

### ISSUE THREAD

**Issue by ThomasWaldmann** [adamgreen/LYWSD02#1]
```
tw@mba2020 LYWSD02 % ./LYWSD02 C
Attempting to connect to LYWSD02 device...
2022-10-30 13:36:25.626 LYWSD02[70966:2889637] Central manager state: Bluetooth is currently powered off.
```

macOS 12.6.1
macbook AIR
Apple Silicon M1 CPU

BT is enabled and I see other BT devices in the device list (but not any LYWDS02).

Any idea what could cause this?

BTW, thank you for writing the code. I currently have the problem that I have no tool to set the clock's time and it is currently 1h off due to the DST change.

**Comment by ThomasWaldmann** [comment]
Strange. I just retried some hours later and now it just worked.

**Comment by adamgreen** [comment]
Hmm...I have seen it give that error before but it has always been accurate and only occurred when I had Bluetooth actually disabled on my Mac.

I have found BLE device discovery isn't reliable for console based applications like this one since around the Big Sur or Catalina releases of macOS. To get it working, I find it best to have a GUI based BLE application like LightBlue running in the background.

**Comment by ThomasWaldmann** [comment]
OK, i installed LightBlue and will try to remember having it running in case I encounter BLE issues, thanks!
